"""Scouter Python package exports."""

# mypy: disable-error-code="attr-defined"
# pylint: disable=no-name-in-module
from . import (
    agent,
    alert,
    bifrost,
    client,
    drift,
    evaluate,
    logging,
    mock,
    observe,
    profile,
    queue,
    service_map,
    trace,
    tracing,
    transport,
    types,
    util,
)
from ._scouter import _get_log_level  # ty: ignore[unresolved-import]
from ._scouter import _log_json  # ty: ignore[unresolved-import]
from ._scouter import (  # dataset; genai
    AgentEvalConfig,
    AgentEvalProfile,
    AggregationType,
    AssertionTask,
    CommonCrons,
    ComparisonOperator,
    CustomDriftProfile,
    CustomMetric,
    CustomMetricAlertConfig,
    CustomMetricDriftConfig,
    DataProfile,
    DataProfiler,
    DatasetClient,
    DatasetProducer,
    Doane,
    Drifter,
    EqualWidthBinning,
    EvalRecord,
    EvalResults,
    FeatureMap,
    Features,
    FreedmanDiaconis,
    GrpcConfig,
    HttpConfig,
    KafkaConfig,
    LLMJudgeTask,
    LoggingConfig,
    Manual,
    Metric,
    Metrics,
    PsiAlertConfig,
    PsiDriftConfig,
    PsiDriftMap,
    PsiDriftProfile,
    QuantileBinning,
    Queue,
)
from ._scouter import QueueFeature as Feature
from ._scouter import (  # dataset; genai
    RabbitMQConfig,
    RedisConfig,
    Rice,
    RustyLogger,
    Scott,
    ScouterClient,
    ScouterQueue,
    SpanFilter,
    SpanStatus,
    SpcAlertConfig,
    SpcDriftConfig,
    SpcDriftMap,
    SpcDriftProfile,
    SpcFeatureDrift,
    SpcFeatureDriftProfile,
    SquareRoot,
    Sturges,
    TableConfig,
    TerrellScott,
    TraceAssertion,
    TraceAssertionTask,
    WriteConfig,
)
from .bifrost import Bifrost
from .service_map import ServiceConnectionRecord, ServiceMapMiddleware

# Configure Rust logging for Python based on environment variables
RustyLogger.setup_logging(
    LoggingConfig(
        log_level=_get_log_level(),
        use_json=_log_json(),
    )
)

__all__ = [
    "alert",
    "bifrost",
    "client",
    "drift",
    "evaluate",
    "agent",
    "logging",
    "mock",
    "observe",
    "profile",
    "queue",
    "trace",
    "tracing",
    "transport",
    "types",
    "util",
    # top-level imports
    "Drifter",
    "SpcDriftConfig",
    "SpcDriftProfile",
    "SpcFeatureDriftProfile",
    "SpcFeatureDrift",
    "SpcDriftMap",
    "PsiDriftConfig",
    "PsiDriftProfile",
    "PsiDriftMap",
    "FeatureMap",
    "CustomMetric",
    "CustomDriftProfile",
    "CustomMetricDriftConfig",
    "QuantileBinning",
    "EqualWidthBinning",
    "Manual",
    "SquareRoot",
    "Sturges",
    "Rice",
    "Doane",
    "Scott",
    "TerrellScott",
    "FreedmanDiaconis",
    "DataProfiler",
    "DataProfile",
    "ScouterQueue",
    "Queue",
    "Feature",
    "Features",
    "Metric",
    "Metrics",
    "CommonCrons",
    "PsiAlertConfig",
    "SpcAlertConfig",
    "CustomMetricAlertConfig",
    "ScouterClient",
    "Bifrost",
    "DatasetClient",
    "DatasetProducer",
    "TableConfig",
    "WriteConfig",
    "HttpConfig",
    "GrpcConfig",
    "KafkaConfig",
    "RabbitMQConfig",
    "RedisConfig",
    # genai
    "AgentEvalConfig",
    "AgentEvalProfile",
    "EvalRecord",
    "LLMJudgeTask",
    "AssertionTask",
    "ComparisonOperator",
    "EvalResults",
    "TraceAssertion",
    "TraceAssertionTask",
    "SpanStatus",
    "AggregationType",
    "SpanFilter",
    # service map
    "service_map",
    "ServiceConnectionRecord",
    "ServiceMapMiddleware",
]
