comment: false

ignore:
  - "tests"
  - "python/scouter/version.py"
  - "python/scouter/utils/comparison/*"
  - "python/scouter/version.py"

coverage:
  range: "70...100"
  status:
    patch:
      default:
        target: 70%
        threshold: 10% 

    project:
      default:
        target: 70%
        threshold: 10% 
        if_ci_failed: error #success, failure, error, ignore