-- Add migration script here
CREATE TABLE IF NOT exists scouter.drift_alert (
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  name text not null,
  space text not null,
  version text not null,
  feature text not null,
  alert jsonb not null default '{}',
  status text not null default 'active',
  id integer generated by default as identity,
  UNIQUE (created_at,name,space,version)
)
PARTITION BY RANGE (created_at);

CREATE INDEX ON scouter.drift_alert (name, space, version, created_at);

SELECT scouter.create_parent(
    'scouter.drift_alert',
    'created_at',
    '1 day'
);

UPDATE scouter.part_config SET retention = '21 days' WHERE parent_table = 'scouter.alert';

