[package]
name = "py-scouter"
version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "scouter"
crate-type = ["cdylib", "rlib"]


[dependencies]
scouter = { workspace = true }
pyo3 = { version = "0.21", features = ["extension-module"] }
numpy = "0.21.0"
num-traits = "0.2.19"
noisy_float = "0.2.0"
ndarray-stats = "0.5.1"
tracing-subscriber = {version = "0.3.18"}
time = "0.3.36"
tracing = "0.1.40"

[profile.release]
lto = "fat"
codegen-units = 1
strip = true
