name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  PACKAGE_NAME: scouter
  INTERPRETER: '3.9 3.10 3.11 3.12 pypy3.9 pypy3.10'
  RUSTFLAGS: -C debuginfo=0

jobs:
  rust-release:
    environment: crates.io
    name: Release-Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - name: cache rust
        id: cargo_release_cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-release

      - name: Switch to main branch
        run: git checkout main

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_REGISTRY_TOKEN }}